### ISSUE TITLE
TIFF uploads are broken when plugin is active

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [pqina/filepond-plugin-image-crop#1]
The crop plugin seems to break TIFF uploads. When enabled and adding a TIFF file (image/tiff) I'm getting an "Uncaught (in promise)" error triggered on line 263. Could it be that `loadImage(url).then(function(image) {` cannot actually handle TIFF files?

**Comment by rikschennink** [comment]
I don't think TIFF support is very uniform across multiple browsers so it might not work. I found this feature table:
https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support

**Comment by SanderVanLeeuwen** [comment]
Hm, you're right. It does work in Safari (albeit without preview). The thing is though that the whole upload fails because of this. It would be nice if only the crop would fail silently (which I'm only using for the upload-preview anyway) but the upload be completed. Would that be possible with some type of feature detection maybe?

**Comment by rikschennink** [comment]
Would be nice indeed. I'll see if I can reproduce it tomorrow and push a fix version.

**Comment by rikschennink** [comment]
Jesus, it's been 14 days :\ I'm looking into it now.

**Comment by rikschennink** [comment]
Just published version `1.0.3` of the image crop plugin, it should fix this issue, might have to update the image preview plugin as well.

**Comment by SanderVanLeeuwen** [comment]
> Jesus, it's been 14 days :\ I'm looking into it now.

Don't worry, I'm not so fast in replying myself either 🙈

With version `1.0.3` the pond doesn't break anymore, but uploading tiffs in Chrome still doesn't work. The uploader hangs on `Waiting for size` when adding a tiff. No errors in the console though.

All plugins are up to date (image-crop `1.0.3`, image-preview `2.0.1`, validate-size `1.0.1` and validate-type `1.1.0`). 

Do you have any idea where I can search for the possible problem?

**Comment by SanderVanLeeuwen** [comment]
Looks like the issue is in the `image-validate-size` plugin. In `getImageSize`, the naturalWidth and naturalHeight on line 25 are always 0, resulting in an endless loop. A quick fix would be to strictly check if the result is `false` or `0`, but that doesn't change the fact that it seems impossible to actually get the tiff's pixel dimensions.

**Comment by rikschennink** [comment]
Thanks for testing, will look into it ASAP

**Comment by rikschennink** [comment]
I've added an error state to the image size plugin so that it at least fails gracefully when it can't determine the image size. Just published a new version.

There are libraries out there that can read dimensions of multiple (not supported) image formats among which is TIFF. It could be an option to add such a library but it would increase the file size of the plugin and slow down its performance. At the same time, these libraries so far as I could tell did not support all types of TIFFs so there would still be situations that cannot be dealt with.

Another option is to add an option to allow the developer (you) to insert their own logic to the measuring image function which would allow you to attach one of the above libraries manually. Or write your own logic to measure image sizes that are not supported by the browser in use.

**Comment by SanderVanLeeuwen** [comment]
Thnx, but it doesn't seem to fix my particular case. The method `getImageSize` doesn't throw an error, but `image.naturalWidth` keeps returning `0` so `getImageSize` never actually reports back to the validator. 

Maybe it's an idea to handle a natural width / height of `0` as an error so that it can be handled (or ignored) accordingly?

I agree that it would be crazy to add large libraries to support some edge cases while it's not even sure they'll cover all cases.

**Comment by SanderVanLeeuwen** [comment]
Additionally, the image size validation is only used as an indication anyway. The real validation is done serverside to be sure it can't be tampered with.

Very happy with FilePond btw. I'm using it to upload files directly to S3 (with a pre-signed request), circumventing file handling on our own servers completely. File type / size / dimension validation is then done using the AWS API gateway and a Lambda script, as is the (on the fly) generation of thumbnails. Sounds like a complex setup, but it's amazingly fast 🚀

**Comment by rikschennink** [comment]
> Thnx, but it doesn't seem to fix my particular case. The method getImageSize doesn't throw an error, but image.naturalWidth keeps returning 0 so getImageSize never actually reports back to the validator.

I had forgotten to clear the image size measure interval when the image onerror callback is triggered. I'm not sure if that makes a difference but I could not reproduce your situation (tried with a small and large TIFF).

> Maybe it's an idea to handle a natural width / height of 0 as an error so that it can be handled (or ignored) accordingly?

 As long as images have not loaded a tiny bit the width and height info is `0` the measure constantly tests if the info is there, and if it is, it stops loading and returns the size information. So I can't really use `0` for that, maybe a timeout would be useful but to be able to implement something like that I would need to be able to reproduce the problem.

> I agree that it would be crazy to add large libraries to support some edge cases while it's not even sure they'll cover all cases.

I've just published a new version with the fix above and have added an additional property `imageValidateSizeMeasure` that allows custom measuring. It's only a couple of bytes but adds a lot of flexibility.

```js
imageValidateSizeMeasure: file => new Promise((resolve, reject) => {
                
    // can't determine size for this file type
    reject(); return;

    // resolve if width and height defined, return as size object
    resolve({
        width: 100,
        height: 100
    });
})
```

> Very happy with FilePond btw. I'm using it to upload files directly to S3 (with a pre-signed request), circumventing file handling on our own servers completely. File type / size / dimension validation is then done using the AWS API gateway and a Lambda script, as is the (on the fly) generation of thumbnails. Sounds like a complex setup, but it's amazingly fast 🚀

That sounds awesome! I've experimented with this a bit but haven't had time to dive in further (the AWS option forest was quite overwhelming). I'm planning to set up standard server config repo's to integrate with Firebase / S3 / normal backend / etc. That should make it possible to do the following which would make set up a lot easier:

```js
FilePond.create({
    server: createS3Bucket({
        // specific S3 options here
    })
});
```

If you have any useful code snippets or references to useful guides to share, that would be amazing :)

**Comment by SanderVanLeeuwen** [comment]
> I've just published a new version with the fix above and have added an additional property imageValidateSizeMeasure that allows custom measuring. It's only a couple of bytes but adds a lot of flexibility.

Cool, that's a neat hook for me to fix things! Since real validation is done server side anyway, I've just implemented a method which reports the required width and height for files where the dimensions cannot be (easily) determined. A bit nasty but good enough.

> If you have any useful code snippets or references to useful guides to share, that would be amazing :)

Actually, I used https://github.com/pqina/filepond/issues/58 as main reference to implement direct S3 uploads. The process described there is quite straightforward and complete, so apart from some implementation specific details I don't have much to add here haha.

When you are setting up standard server stuff, I think describing or providing a framework for the 'little' details is most important. For example, the S3 requests are pre-signed with filenames that are controlled server side. I'm keeping track of those in a database, but the process is asynchronous. That is, when an upload is canceled or fails for some reason, I also try to get rid of the unnecessary database entry. And when it succeeds, the entry is populated with some additional details fetched from the S3 file. But that's probably a bridge too far in what you're trying to achieve right?

**Comment by rikschennink** [comment]
Ah good to know! Then I'll take a look there hah :D 

I think it might be, I'm also not super familiar with S3, oh well, I'll see where I end up. The idea is that it's a quick component to integrate with the server FilePond property, what happens in the can be anything as long as it returns a file id / updates the progress indicator / etc.
